language: python
python:
  - "2.7"
sudo: required
services: 
  - docker

before_script:

before_install:
  - docker build -t pystache/alpine .

install:

# Running tests
script: 
  - docker run -it pystache/alpine pystache-test

after_success:

after_failure:
